# Generated by Django 4.2.3 on 2024-11-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_exercise_exercise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietlogitem',
            name='food_name',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
