# Generated by Django 4.2.3 on 2024-11-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_dietlogitem_food_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='image_url',
            field=models.URLField(default='https://static.vecteezy.com/ti/vecteur-libre/p1/15158839-logo-de-fitness-et-d-halterophilie-symbole-d-illustrationle-vectoriel.jpg'),
            preserve_default=False,
        ),
    ]
